### ISSUE TITLE
Use constructor tear-off when building the response 

### ISSUE THREAD

**Issue by rutesantos4** [dart-pacotes/networking#19]
In the class lib/src/http/clients/networking_client.dart you have a switch case when creating the response. I recommend using the constructor tear-off instead.

**Comment by freitzzz** [comment]
> In the class lib/src/http/clients/networking_client.dart you have a switch case when creating the response. I recommend using the constructor tear-off instead. 

That sure is the case! Thanks for the suggestion, I will later apply a refactor
